// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAI51tK0r8Kj_p_AiVg1FvrGmfp4n2Vso',
    appId: '1:401939792245:web:3ec6bb426de526670e533c',
    messagingSenderId: '401939792245',
    projectId: 'study-support-app-group',
    authDomain: 'study-support-app-group.firebaseapp.com',
    storageBucket: 'study-support-app-group.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRm1meRZhTSkRpLZSu8A0BIEhcdeQLVgo',
    appId: '1:401939792245:android:e0170bdf4f5ebb680e533c',
    messagingSenderId: '401939792245',
    projectId: 'study-support-app-group',
    storageBucket: 'study-support-app-group.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZY4sVDtoLqYFmSFx2BJb6n88bcXDPDIo',
    appId: '1:401939792245:ios:2f8fda764096c18d0e533c',
    messagingSenderId: '401939792245',
    projectId: 'study-support-app-group',
    storageBucket: 'study-support-app-group.firebasestorage.app',
    iosBundleId: 'com.example.studySupportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZY4sVDtoLqYFmSFx2BJb6n88bcXDPDIo',
    appId: '1:401939792245:ios:2f8fda764096c18d0e533c',
    messagingSenderId: '401939792245',
    projectId: 'study-support-app-group',
    storageBucket: 'study-support-app-group.firebasestorage.app',
    iosBundleId: 'com.example.studySupportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAI51tK0r8Kj_p_AiVg1FvrGmfp4n2Vso',
    appId: '1:401939792245:web:45593dc26466621f0e533c',
    messagingSenderId: '401939792245',
    projectId: 'study-support-app-group',
    authDomain: 'study-support-app-group.firebaseapp.com',
    storageBucket: 'study-support-app-group.firebasestorage.app',
  );
}
